[project]
name = "utils-layer"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.114.0",
    "fastapi-cli==0.0.5",
    "pydantic==2.9.0",
    "pydantic-core==2.23.2",
    "mangum==0.17.0",
    "pyyaml>=6.0.0",
]
